### PR TITLE
CrystalDiskInfo: Add version 8.14.2

### LINKED ISSUE #93: [Request] Add CrystalDiskInfo
### Package Name

CrystalDiskInfo

### Latest version

8.14.2

### Description

A HDD/SSD utility software which supports a part of USB, Intel RAID and NVMe.

### Homepage

https://osdn.net/projects/crystaldiskinfo

### License

MIT

### Graphical interface

Yes

### Portable version

Yes

### Some indication of popularity/repute

4841

### Download link(s)

```powershell
https://osdn.dl.osdn.net/crystaldiskinfo/76547/CrystalDiskInfo8_14_2.zip
```

### Else

_No response_

### PR DESCRIPTION
**Pull request by Ryanjiena**
CrystalDiskInfo: Add version 8.14.2

CrystalDiskInfo-tuna: Add version 8.14.2

CrystalDiskInfo-Shizuku: Add version 8.14.2

CrystalDiskInfo-Shizuku-tuna: Add version 8.14.2

CrystalDiskInfo-KureiKei: Add version 8.14.2

CrystalDiskInfo-KureiKei-tuna: Add version 8.14.2

Fixes #93

### CODE REVIEW

**Comment by JaimeZeng** [comment]
[Your changes do not pass checks.](https://github.com/Ash258/Scoop-GithubActions/wiki/Pull-Request-Checks)
### CrystalDiskInfo-KureiKei-tuna

- [x] Description
- [x] License
- [x] Hashes
- [ ] Checkver
- [ ] Autoupdate
- [ ] Autoupdate Hash Extraction

### CrystalDiskInfo-KureiKei

- [x] Description
- [x] License
- [x] Hashes
- [x] Checkver
- [x] Autoupdate
- [x] Autoupdate Hash Extraction

### CrystalDiskInfo-Shizuku-tuna

- [x] Description
- [x] License
- [x] Hashes
- [x] Checkver
- [x] Autoupdate
- [x] Autoupdate Hash Extraction

### CrystalDiskInfo-Shizuku

- [x] Description
- [x] License
- [x] Hashes
- [x] Checkver
- [x] Autoupdate
- [x] Autoupdate Hash Extraction

### CrystalDiskInfo-tuna

- [x] Description
- [x] License
- [x] Hashes
- [x] Checkver
- [x] Autoupdate
- [x] Autoupdate Hash Extraction

### CrystalDiskInfo

- [x] Description
- [x] License
- [x] Hashes
- [x] Checkver
- [x] Autoupdate
- [x] Autoupdate Hash Extraction

**Comment by Ryanjiena** [comment]
image

**Pull request merged**
